### ISSUE TITLE
Figure out `GetRequireHeight`

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/gen2-energi-seeder#1]
In the seeder, there's a function called `GetRequireHeight`, which essentially returns the acceptable height for a "good" (read: responsible) nodes. It's always 0 for testnet but we might need to adjust it for the mainnet.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure out `GetRequireHeight`](https://trello.com/c/AKKLcMpY/57-figure-out-getrequireheight)
